# Generated by Django 2.1.2 on 2018-10-14 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reader_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('time_spent', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='media_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=models.TextField(default='PROBLEM GETTING ARTICLE TEXT'),
        ),
        migrations.AddField(
            model_name='reader_log',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.article'),
        ),
        migrations.AddField(
            model_name='reader_log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user_reader'),
        ),
    ]
